parameters:
- name: environmentVariables
  type: string
- name: serviceConnection
  type: string
- name: environment
  type: string


jobs:
- job: build

  variables:
    - group: ${{parameters.environmentVariables}}
    - group: synapse-analytics
    - name: rule_name
      value: RoozbehBandpey
    - name: start_ip
      value: "0.0.0.0"
    - name: end_ip
      value: "0.0.0.0"

  pool:
      name: Athena-CPU-Deep-$(environment)

  timeoutInMinutes: 120

  steps:    
  - task: AzureCLI@2
    displayName: Opening ips
    inputs:
      azureSubscription: ${{parameters.serviceConnection}}
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        set -ex

        rules=$(az sql server firewall-rule list \
              --server synapse-analytics-sqls-${{parameters.environment}} \
              --resource-group synapse-analytics-${{parameters.environment}} \
              --subscription $(subscriptionId) \
              --query 'length([?name=="$(rule_name)"])')

        if [ $rules -eq 0 ]; then
          echo "Creating rule $(rule_name)"
          az sql server firewall-rule create \
              --server synapse-analytics-sqls-${{parameters.environment}} \
              --resource-group synapse-analytics-${{parameters.environment}} \
              --subscription $(subscriptionId) \
              --name $(rule_name) \
              --start-ip-address $(start_ip) \
              --end-ip-address $(end_ip)
        else
          echo "Updating rule $(rule_name)"
          az sql server firewall-rule update \
              --server synapse-analytics-sqls-${{parameters.environment}} \
              --resource-group synapse-analytics-${{parameters.environment}} \
              --subscription $(subscriptionId) \
              --name $(rule_name) \
              --start-ip-address $(start_ip) \
              --end-ip-address $(end_ip)
        fi
    