name: azureml
channels:
  - defaults
dependencies:
  - python=3.7.7
  - scikit-learn=0.22.1
  - pip
  - pip:
    - azureml-defaults>=1.0.45
    - inference-schema[numpy-support]
    - transformers
    - torch
    - spacy
    - dateparser
    - opencensus==0.7
    - opencensus-ext-azure==1
    - datefinder
    - babel
    - price-parser
    - forex_python

