name: bert
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - pip
  - pip:
    - torch==1.6.0
    - adal==1.2.4
    - applicationinsights==0.11.9
    - argcomplete==1.12.0
    - azure-cli-command-modules-nspkg==2.0.3
    - azure-cli-nspkg==3.0.4
    - azure-common==1.1.25
    - azure-core==1.8.0
    - azure-cosmos==3.2.0
    - azure-identity==1.2.0
    - azure-keyvault==1.1.0
    - azure-loganalytics==0.1.0
    - azure-mgmt-advisor==2.0.1
    - azure-mgmt-apimanagement==0.2.0
    - azure-mgmt-applicationinsights==0.1.1
    - azure-mgmt-batchai==2.0.0
    - azure-mgmt-billing==0.2.0
    - azure-mgmt-cdn==3.1.0
    - azure-mgmt-consumption==2.0.0
    - azure-mgmt-containerinstance==1.5.0
    - azure-mgmt-containerregistry==3.0.0rc14
    - azure-mgmt-datalake-analytics==0.2.1
    - azure-mgmt-datalake-nspkg==3.0.1
    - azure-mgmt-datalake-store==0.5.0
    - azure-mgmt-deploymentmanager==0.1.0
    - azure-mgmt-devtestlabs==2.2.0
    - azure-mgmt-dns==2.1.0
    - azure-mgmt-eventhub==2.6.0
    - azure-mgmt-hdinsight==1.1.0
    - azure-mgmt-imagebuilder==0.2.1
    - azure-mgmt-iotcentral==1.0.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-loganalytics==0.7.0
    - azure-mgmt-managementgroups==0.2.0
    - azure-mgmt-maps==0.1.0
    - azure-mgmt-media==1.1.1
    - azure-mgmt-msi==0.2.0
    - azure-mgmt-netapp==0.7.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-recoveryservicesbackup==0.4.0
    - azure-mgmt-resource==4.0.0
    - azure-mgmt-search==2.1.0
    - azure-mgmt-security==0.1.0
    - azure-mgmt-servicefabric==0.2.0
    - azure-mgmt-signalr==0.3.0
    - azure-mgmt-storage==5.0.0
    - azure-mgmt-trafficmanager==0.51.0
    - azure-multiapi-storage==0.2.4
    - azure-nspkg==3.0.2
    - azure-storage-blob==12.4.0
    - azure-storage-common==2.1.0
    - azureml-automl-core==1.12.0
    - azureml-core==1.12.0.post1
    - azureml-dataprep==2.0.7
    - azureml-dataprep-native==20.0.2
    - azureml-dataset-runtime==1.12.0
    - azureml-pipeline==1.12.0
    - azureml-pipeline-core==1.12.0
    - azureml-pipeline-steps==1.12.0
    - azureml-sdk==1.12.0
    - azureml-telemetry==1.12.0
    - azureml-train==1.12.0
    - azureml-train-automl-client==1.12.0.post1
    - azureml-train-core==1.12.0
    - azureml-train-restclients-hyperdrive==1.12.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.0
    - cloudpickle==1.5.0
    - contextlib2==0.6.0.post1
    - distro==1.5.0
    - docker==4.3.1
    - dotnetcore2==2.1.14
    - filelock==3.0.12
    - fusepy==3.0.1
    - future==0.18.2
    - isodate==0.6.0
    - jeepney==0.4.3
    - jinja2==2.11.2
    - jsonpickle==1.4.1
    - knack==0.7.2
    - markupsafe==1.1.1
    - msal==1.4.3
    - msal-extensions==0.1.3
    - msrest==0.6.18
    - msrestazure==0.6.4
    - ndg-httpsclient==0.5.1
    - numpy==1.16.2
    - oauthlib==3.1.0
    - paramiko==2.7.1
    - pathspec==0.8.0
    - portalocker==1.7.1
    - psutil==5.7.2
    - pyarrow==1.0.1
    - pyasn1==0.4.8
    - pydocumentdb==2.3.5
    - pygments==2.6.1
    - pyjwt==1.7.1
    - pynacl==1.4.0
    - pyreadline==2.1
    - pytz==2019.1
    - pywin32==227
    - pyyaml==5.3.1
    - requests-oauthlib==1.3.0
    - ruamel-yaml==0.15.89
    - ruamel-yaml-clib==0.2.0
    - scipy==1.1.0
    - scp==0.13.2
    - secretstorage==3.1.2
    - sentencepiece==0.1.91
    - tabulate==0.8.7
    - tokenizers==0.8.1rc1
    - transformers==3.0.2
    - websocket-client==0.56.0
    - atomicwrites==1.4.0
    - attrs==20.1.0
    - autopep8==1.5.4
    - blas==1.0
    - boto3==1.14.47
    - botocore==1.17.47
    - brotlipy==0.7.0
    - ca-certificates==2020.6.20
    - certifi==2020.6.20
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - colorama==0.4.3
    - cryptography==2.9.2
    - cudatoolkit==10.2.89
    - cycler==0.10.0
    - docutils==0.15.2
    - freetype==2.10.2
    - icc_rt==2019.0.0
    - icu==58.2
    - idna==2.10
    - importlib-metadata==1.7.0
    - importlib_metadata==1.7.0=0
    - iniconfig==1.0.1
    - intel-openmp==2020.1
    - jmespath==0.10.0
    - joblib==0.16.0
    - jpeg==9b
    - kiwisolver==1.2.0
    - libpng==1.6.37
    - libtiff==4.1.0
    - lz4=-c=1.9.2
    - matplotlib==3.3.1
    - matplotlib=-base=3.3.1
    - mkl==2020.1
    - mkl=service==2.3.0
    - mkl_fft==1.1.0
    - mkl_random==1.1.1
    - more-itertools==8.4.0
    - ninja==1.10.0
    - numpy-base==1.19.1
    - nvidia-apex==0.1
    - olefile==0.46
    - openssl==1.1.1g
    - packaging==20.4
    - pandas==1.1.0
    - pillow==7.2.0
    - pip==20.2.2
    - pluggy==0.13.1
    - py==1.9.0
    - pycodestyle==2.6.0
    - pycparser==2.20
    - pyopenssl==19.1.0
    - pyparsing==2.4.7
    - pyqt==5.9.2
    - pysocks==1.7.1
    - pytest==6.0.1
    - python==3.7.7
    - python-dateutil==2.8.1
    - python_abi==3.7
    - qt==5.9.7
    - regex==2020.7.14
    - requests==2.24.0
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit=-learn=0.23.1
    - setuptools==49.6.0
    - sip==4.19.8
    - six==1.15.0
    - sqlite==3.32.3
    - threadpoolctl==2.1.0
    - tk==8.6.10
    - toml==0.10.1
    - tornado==6.0.4
    - tqdm==4.48.2
    - urllib3==1.25.10
    - vc==14.1
    - vs2015_runtime==14.16.27012
    - wheel==0.34.2
    - win_inet_pton==1.1.0
    - wincertstore==0.2
    - xz==5.2.5
    - yaml==0.2.5
    - zipp==3.1.0
    - zlib==1.2.11
    - zstd==1.4.5

